### ISSUE TITLE
eval in quick-sort.js gives err when used in chrome extension.

### ISSUE THREAD

**Issue by YuanboXue-Amber** [7rulnik/source-map-js#15]
Hi, I'm using source-map-js in a chrome extension. However I'm getting error 'Refuse to evaluate a string as JavaScript...', because quick-sort.js is using `new Function()`, and it is a eval-like structure. 
I found out this is introduced by #2. 
Would it be possible to release a version of source-map-js without the evaluation?

**Comment by 7rulnik** [comment]
@YuanboXue-Amber hi! Sorry for really late response.

Well, I guess it's not possible because the whole idea of this project — speed up source-map JS implementation in node.js.
I saw you patched package which is fine I think. I can suggest to find another implementation which will be fast and will not require patching for you. You can pick something from this issue https://github.com/tc39/source-map/issues/47

You can find more details here https://mrale.ph/blog/2018/02/03/maybe-you-dont-need-rust-to-speed-up-your-js.html#optimizing-sorting---monomorphisation
